version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Sofia
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.4
